version: '2.2'

services:
  web:
    image: 'docker-spring-boot-ecommerce:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=dynamic
      - POSTGRES_PASSWORD=dynamic
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
